update yml file

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -1,4 +1,4 @@
-on: 
+on:
   push:
     branches:
       - master
@@ -8,59 +8,59 @@ jobs:
     name: 🎉 Deploy
     runs-on: ubuntu-latest
     steps:
-    # Runs a single command using the runners shell
-    - name: Ls
-      run: ls -la    
-  
-    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can have access to it
-    - name: Git Clone
-      uses: actions/checkout@v4
-      with:
-        ref: 'master'
-        
-    # Runs a single command using the runners shell
-    - name: Ls
-      run: ls -la
+      # Runs a single command using the runners shell
+      - name: Ls
+        run: ls -la
 
-    # Install composer
-    - name: Install composer dependencies
-      run: composer install --no-scripts 
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can have access to it
+      - name: Git Clone
+        uses: actions/checkout@v4
+        with:
+          ref: "master"
 
-    # PHPUnit tests
-    - name: PHPUnit tests
-      run: php artisan test
+      # Runs a single command using the runners shell
+      - name: Ls
+        run: ls -la
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: '21.7.2'
-        
-    - name: Install Node.js Dependencies
-      run: npm install
+      # Install composer
+      - name: Install composer dependencies
+        run: composer install --no-scripts
 
-    - name: Build Assets
-      run: npm run prod
+      # PHPUnit tests
+      - name: PHPUnit tests
+        run: php artisan test
 
-    - name: Create Deployment Archive
-      env: 
-        GITHUB_SHA: ${{ github.sha }}
-      run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules *
-  
-    # configure php
-    - name: Setup PHP Action
-      uses: shivammathur/setup-php@2.30.4
-      with:
-        php-version: '8.3'
-        extensions: imagick, swoole, openssl
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "21.7.2"
 
-    # store artifacts for distribution
-    - name: store artifacts for distribution
-      uses: actions/upload-artifact@v4
-      with:
-        name: app-build
-        path: ${{ github.sha}}.tar.gz
+      - name: Install Node.js Dependencies
+        run: npm install
 
-# Prepairing release on server
+      - name: Build Assets
+        run: npm run prod
+
+      - name: Create Deployment Archive
+        env:
+          GITHUB_SHA: ${{ github.sha }}
+        run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules *
+
+      # configure php
+      - name: Setup PHP Action
+        uses: shivammathur/setup-php@2.30.4
+        with:
+          php-version: "8.3"
+          extensions: imagick, swoole, openssl
+
+      # store artifacts for distribution
+      - name: store artifacts for distribution
+        uses: actions/upload-artifact@v4
+        with:
+          name: app-build
+          path: ${{ github.sha}}.tar.gz
+
+  # Prepairing release on server
   ssh-release:
     name: ssh-release
     runs-on: ubuntu-latest
@@ -80,8 +80,15 @@ jobs:
           target: /home/printsh1/print.printshopeld/artifacts
       - name: extract archive and create directory
         uses: appleboy/ssh-action@master
-        env: 
+        env:
           GITHUB_SHA: ${{ github.sha }}
+          SOURCE_ASSET_DIR: /home/printsh1/print.printshopeld/release/${{github.sha}}/public/assets
+          SOURCE_CSS_DIR: /home/printsh1/print.printshopeld/release/${{github.sha}}/public/assets
+          SOURCE_JS_DIR: /home/printsh1/print.printshopeld/release/${{github.sha}}/public/assets
+          DEST_ASSET_DIR: /home/printsh1/print.printshopeld.com/phptelebot/public/assets
+          DEST_CSS_DIR: /home/printsh1/print.printshopeld.com/phptelebot/public/css
+          DEST_JS_DIR: /home/printsh1/print.printshopeld.com/phptelebot/public/js
+          DEST_PARENT_DIR: /home/printsh1/print.printshopeld.com/phptelebot/public
         with:
           host: ${{ secrets.SSH_SITES_IP }}
           username: ${{ secrets.FTP_SITES_USER }}
@@ -91,51 +98,80 @@ jobs:
           script: |
             mkdir -p "/home/printsh1/print.printshopeld/release/${GITHUB_SHA}"
             tar xzf /home/printsh1/print.printshopeld/artifacts/${GITHUB_SHA}.tar.gz -C "/home/printsh1/print.printshopeld/release/${GITHUB_SHA}"
-
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
             rm -rf /home/printsh1/print.printshopeld/release/${GITHUB_SHA}/storage
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
             if [ ! -d "/home/printsh1/print.printshopeld/storage" ]; then
             mkdir -p /home/printsh1/print.printshopeld/storage/{app,public,framework,logs}
             mkdir -p /home/printsh1/print.printshopeld/storage/framework/{cache,sessions,testing,views}
             mkdir -p /home/printsh1/print.printshopeld/storage/framework/cache/data
             chmod -R 0777 /home/printsh1/print.printshopeld/storage
             fi
-
-            if [ -d "/home/printsh1/print.printshopeld.com/phptelebot/public/assets" ]; then
-            rm -rf "/home/printsh1/print.printshopeld.com/phptelebot/public/assets"
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+            if [ -d "$SOURCE_ASSET_DIR" ]; then
+                if [ -d "$DEST_ASSET_DIR" ]; then
+                    rm -rf "$DEST_ASSET_DIR"
+                    if [ $? -ne 0 ]; then
+                        echo "Failed to remove the destination asset directory."
+                        exit 1
+                    fi
+                else
+                    echo "asset directory does not exist in the destination."
+                fi
+                mv "$SOURCE_ASSET_DIR" "$DEST_PARENT_DIR"
+                if [ $? -ne 0 ]; then
+                    echo "Failed to move the asset directory from source to destination."
+                    exit 1
+                fi
             else
-                echo "Source directory does not exist. Skipping move operation."
+                echo "asset directory does not exist in the source."
             fi
-            if [ -d "/home/printsh1/print.printshopeld.com/phptelebot/public/css" ]; then
-            rm -rf "/home/printsh1/print.printshopeld.com/phptelebot/public/css"
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+            if [ -d "$SOURCE_CSS_DIR" ]; then
+                if [ -d "$DEST_CSS_DIR" ]; then
+                    rm -rf "$DEST_CSS_DIR"
+                    if [ $? -ne 0 ]; then
+                        echo "Failed to remove the destination css directory."
+                        exit 1
+                    fi
+                else
+                    echo "css directory does not exist in the destination."
+                fi
+                mv "$SOURCE_CSS_DIR" "$DEST_PARENT_DIR"
+                if [ $? -ne 0 ]; then
+                    echo "Failed to move the css directory from source to destination."
+                    exit 1
+                fi
             else
-                echo "Source directory does not exist. Skipping move operation."
+                echo "css directory does not exist in the source."
             fi
-            if [ -d "/home/printsh1/print.printshopeld.com/phptelebot/public/js" ]; then
-            rm -rf "/home/printsh1/print.printshopeld.com/phptelebot/public/js"
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+            if [ -d "$SOURCE_JS_DIR" ]; then
+                if [ -d "$DEST_JS_DIR" ]; then
+                    rm -rf "$DEST_JS_DIR"
+                    if [ $? -ne 0 ]; then
+                        echo "Failed to remove the destination js directory."
+                        exit 1
+                    fi
+                else
+                    echo "js directory does not exist in the destination."
+                fi
+                mv "$SOURCE_JS_DIR" "$DEST_PARENT_DIR"
+                if [ $? -ne 0 ]; then
+                    echo "Failed to move the js directory from source to destination."
+                    exit 1
+                fi
             else
-                echo "Source directory does not exist. Skipping move operation."
+                echo "js directory does not exist in the source."
             fi
-
-            if [ -d "/home/printsh1/print.printshopeld/release/${GITHUB_SHA}/public/assets" ]; then
-            mv "/home/printsh1/print.printshopeld/release/${GITHUB_SHA}/public/assets" "/home/printsh1/print.printshopeld.com/phptelebot/public"
-            else
-                echo "Source directory does not exist. Skipping move operation."
-            fi
-            if [ -d "/home/printsh1/print.printshopeld/release/${GITHUB_SHA}/public/css" ]; then
-            mv "/home/printsh1/print.printshopeld/release/${GITHUB_SHA}/public/css" "/home/printsh1/print.printshopeld.com/phptelebot/public"
-            else
-                echo "Source directory does not exist. Skipping move operation."
-            fi
-            if [ -d "/home/printsh1/print.printshopeld/release/${GITHUB_SHA}/public/js" ]; then
-            mv "/home/printsh1/print.printshopeld/release/${GITHUB_SHA}/public/js" "/home/printsh1/print.printshopeld.com/phptelebot/public"
-            else
-                echo "Source directory does not exist. Skipping move operation."
-            fi
-
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
             mv -f "/home/printsh1/print.printshopeld/release/${GITHUB_SHA}/public/mix-manifest.json" "/home/printsh1/print.printshopeld.com/phptelebot/public"
-            
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
             rm -rf /home/printsh1/print.printshopeld/release/${GITHUB_SHA}/public/
-# Run befor-hooks
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+
+
+  # Run befor-hooks
   run-befor-hook:
     name: befor-hook
     runs-on: ubuntu-latest
@@ -143,7 +179,7 @@ jobs:
     steps:
       - name: run-befor-hooks
         uses: appleboy/ssh-action@master
-        env: 
+        env:
           GITHUB_SHA: ${{ github.sha }}
           RELEASE_PATH: /home/printsh1/print.printshopeld/release/${{github.sha}}
           ACTIVE_RELEASE_PATH: /home/printsh1/print.printshopeld/current
@@ -157,7 +193,7 @@ jobs:
           envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH
           script: |
             echo "${GITHUB_SHA}"
-# Run activate release
+  # Run activate release
   activate-release:
     name: activate-release
     runs-on: ubuntu-latest
@@ -165,7 +201,7 @@ jobs:
     steps:
       - name: run-activate-release
         uses: appleboy/ssh-action@master
-        env: 
+        env:
           GITHUB_SHA: ${{ github.sha }}
           RELEASE_PATH: /home/printsh1/print.printshopeld/release/${{github.sha}}
           ACTIVE_RELEASE_PATH: /home/printsh1/print.printshopeld/current
@@ -184,7 +220,7 @@ jobs:
             ln -s -n -f ${BASE_PATH}/.env $RELEASE_PATH
             ln -s -n -f $STORAGE_PATH $RELEASE_PATH
             ln -s -n -f $RELEASE_PATH $ACTIVE_RELEASE_PATH
-# Run Migrations release
+  # Run Migrations release
   migrations-run:
     name: migrations-run
     runs-on: ubuntu-latest
@@ -192,7 +228,7 @@ jobs:
     steps:
       - name: run-activate-release
         uses: appleboy/ssh-action@master
-        env: 
+        env:
           GITHUB_SHA: ${{ github.sha }}
           RELEASE_PATH: /home/printsh1/print.printshopeld/release/${{github.sha}}
           ACTIVE_RELEASE_PATH: /home/printsh1/print.printshopeld/current
@@ -209,15 +245,22 @@ jobs:
           script: |
             cd $ACTIVE_RELEASE_PATH
             php artisan migrate --force
-# Run activate release
+  # Run activate release
   run-after-hook:
     name: after-hook
     runs-on: ubuntu-latest
-    needs: [web-deploy, ssh-release, run-befor-hook, activate-release, migrations-run]
+    needs:
+      [
+        web-deploy,
+        ssh-release,
+        run-befor-hook,
+        activate-release,
+        migrations-run,
+      ]
     steps:
       - name: run-after-hooks
         uses: appleboy/ssh-action@master
-        env: 
+        env:
           GITHUB_SHA: ${{ github.sha }}
           RELEASE_PATH: /home/printsh1/print.printshopeld/release/${{github.sha}}
           ACTIVE_RELEASE_PATH: /home/printsh1/print.printshopeld/current
@@ -231,15 +274,23 @@ jobs:
           envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH
           script: |
             echo "${GITHUB_SHA}"
-# Run cleanup
+  # Run cleanup
   clean-up:
     name: Clean-up
     runs-on: ubuntu-latest
-    needs: [web-deploy, ssh-release, run-befor-hook, activate-release, migrations-run, run-after-hook]
+    needs:
+      [
+        web-deploy,
+        ssh-release,
+        run-befor-hook,
+        activate-release,
+        migrations-run,
+        run-after-hook,
+      ]
     steps:
       - name: run-clean-up
         uses: appleboy/ssh-action@master
-        env: 
+        env:
           RELEASE_PATH: /home/printsh1/print.printshopeld/release
           ARTIFACTS_PATH: /home/printsh1/print.printshopeld/artifacts
         with:
